# SwiftLint Configuration for VoiceType
# Focuses on catching deprecated syntax and enforcing modern Swift practices

# Paths to include
included:
  - Sources
  - Tests
  - Examples

# Paths to exclude
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - Tests/PerformanceTests # Can exclude performance tests if needed
  - "**/*.generated.swift"

# Rules configuration
opt_in_rules:
  # Deprecated API Detection
  - legacy_constructor
  - legacy_function
  - legacy_hashing
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  
  # Modern Swift Patterns
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # We use TODOs
  - line_length # Can be too restrictive
  - file_length # Some files are necessarily long
  - type_body_length # Some types are complex
  - function_body_length # Some functions are complex

# Rule configurations
force_cast: warning
force_try: warning

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - r1
    - r2

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 20

file_length:
  warning: 600
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 4

# Custom Rules for Deprecated Syntax
custom_rules:
  deprecated_selector_syntax:
    name: "Deprecated Selector Syntax"
    regex: 'Selector\(\('
    message: "Use #selector syntax instead of Selector(("
    severity: error
    
  deprecated_nsapp:
    name: "Avoid Direct NSApp Usage"
    regex: '\bNSApp\b'
    message: "Consider using NSApplication.shared for clarity"
    severity: warning
    excluded:
      - ".*AppDelegate.*"
      - ".*VoiceTypeApp.*"
    
  deprecated_string_format:
    name: "Deprecated String Format"
    regex: 'String\(format:'
    message: "Consider using String interpolation or formatted() instead"
    severity: warning
    
  avoid_print:
    name: "Avoid Print Statements"
    regex: '\bprint\('
    message: "Use proper logging instead of print statements"
    severity: warning
    excluded:
      - ".*Tests/.*"
      - ".*Example.*"
      
  deprecated_dispatch:
    name: "Deprecated Dispatch Patterns"
    regex: 'DispatchQueue\.global\(\)\.async'
    message: "Consider using Task { } for async work"
    severity: warning
    
  force_unwrap_iboutlet:
    name: "Force Unwrapping IBOutlet"
    regex: '@IBOutlet\s+weak\s+var\s+\w+:\s+\w+!'
    message: "Avoid force unwrapping IBOutlets"
    severity: warning
    
  deprecated_notification_center:
    name: "Deprecated NotificationCenter Pattern"
    regex: 'NSNotification\.Name\('
    message: "Use Notification.Name with static extensions"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"

# SwiftLint configuration for specific files or patterns
analyzer_rules:
  - explicit_self
  - unused_import

# Configure warnings vs errors
warning_threshold: 10